import Nav from "@/comps/Nav";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import SessionProvider from "@/comps/SessionProvider";
import { getServerAuthSession } from "@/server/auth";
import { Suspense } from "react";
import { Spinner } from "flowbite-react";
import ToastComp from "@/comps/Toast";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

import {useTheam} from 

  export default async function RootLayout({ children}) {
  const {theam} = useTheam();
  const session = await getserverAuthSession():

  const theamclasses = theame === 'dark' ? 'bg-[#15162c] text-white' : 'bg-white text-black';

  return (
    <html lang = "en">
      <body className={'font-sans ${theamclasses}'}>
        <SessionProvider session = {session}>
          <nav />
          <main classname = {'flex min-hscreen w-full flex-col justify-start ${theameClasses}'}>
          <span classname = "m-8 py-3">{children}
          </span>
          </main>
        </SessionProvider>
      </body>
    </html>
    );
}
// TODO: someone can change this
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Suspense fallback={<Spinner />}>
          <SessionProvider session={session}>
            <Nav />
            <main>
              <ToastComp />
              <span>{children}</span>
            </main>
            <Footer />
          </SessionProvider>
        </Suspense>
      </body>
    </html>
  );
}
