import Nav from "@/comps/Nav";
import { Inter } from "next/font/google";

import SessionProvider from "@/comps/SessionProvider";
import { getServerAuthSession } from "@/server/auth";
import { Suspense } from "react";
import { Spinner } from "flowbite-react";
import "../styles/index.css";
import "../styles/prism-vsc-dark-plus.css";
import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

// TODO: someone can change this
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
        <Suspense fallback={<Spinner />}>
          <SessionProvider session={session}>
            <Nav />
            <main>
              <span>{children}</span>
              <Footer />
            </main>
          </SessionProvider>
        </Suspense>
      </body>
    </html>
  );
}
