name: Build Dev
on:
  pull_request:
    branches:
      - development
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
