name: Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PROJECT_ID }}
  PREVIEW_URL: trophy-tracker-wsu-preview.vercel.app
  PROD_URL: trophy-tracker-wsu.vercel.app
  NEXTAUTH_URL: https://trophy-tracker-wsu.vercel.app
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  GITHUB_SECRET: ${{ secrets.GH_SECRET }}
  GITHUB_ID: ${{ secrets.GH_ID }}
  MONGODB_URI: ${{ secrets.MONGODB_URI }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Install Dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"
      - name: Install Dependencies
        run: |
          npm install
          npm install -g vercel
      - name: Deploy
        run: |
          # if it's a push to main or development branch or workflow_dispatch deploy to production.
          if [ ${{ github.event_name == 'push' }} ] && [ ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development' }} ] || [ ${{ github.event_name == 'workflow_dispatch' }} ]
          then
            vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
          else
            # get preview url
            url="$(vercel deploy --token=${{ secrets.VERCEL_TOKEN }})"
            vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" "$PREVIEW_URL"
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  comment:
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Comment to pr
        uses: KeisukeYamashita/create-comment@v1
        with:
          comment: >
            View Vercel deployments:

            [Visit Preview](https://trophy-tracker-wsu-preview.vercel.app) - :warning:
            [Visit Production](https://trophy-tracker-wsu.vercel.app) - Deployed :white_check_mark:
            # ${{ github.event.pull_request.base.ref == 'development' && '[Visit Preview](https://trophy-tracker-wsu-preview.vercel.app)' || '' }}
            # ${{ github.event.pull_request.base.ref == 'main' && '[Visit Production](https://trophy-tracker-wsu.vercel.app)' || '' }}

        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
